name: Commit Linting ğŸ›ï¸

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  archunit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Checker ğŸ”
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.1
