name: Architecture Tests ğŸ›ï¸

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  archunit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources ğŸ“„
        uses: actions/checkout@v6

      - uses: bugbundle/commits@v1.1.0
        id: commits

      - run: |
          echo ${{ steps.commits.outputs.major }}.${{ steps.commits.outputs.minor }}.${{ steps.commits.outputs.patch }}
