name: Verifier ðŸ”Ž

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources ðŸ“„
        uses: actions/checkout@v6

      - name: Setup Java â˜•
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 24

      - name: Setup Gradle ðŸ’¾
        uses: gradle/actions/setup-gradle@v4

      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker

      - name: Run backend tests ðŸ§ª
        run: ./backend/gradlew -p ./backend/ build
